//Human Age
const myAge = 34;

//Dog early Years
let earlyYears = 2;

earlyYears *= 10.5;

//
let laterYears = myAge - 2;
//
laterYears *= 4;

console.log(earlyYears);
console.log(laterYears);

myAgeInDogYears = earlyYears + laterYears;
//

const myName = "Kunjan Patel".toLowerCase();
console.log(
  `My name is ${myName}. I am ${myAge} years old in human years which is ${myAgeInDogYears} years old in dog years`
);
